# Generated by Django 5.1.3 on 2024-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='registrationDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
