# Generated by Django 5.1.3 on 2024-12-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_alter_telegramuser_registrationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegramUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuizAnswer', to='zoo.telegramuser', verbose_name='Telegram User')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_animal', models.CharField(max_length=255)),
                ('reasoning', models.JSONField()),
                ('care_recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegramUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuizResult', to='zoo.telegramuser', verbose_name='Telegram User')),
            ],
        ),
    ]
