# Generated by Django 5.1.3 on 2025-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_telegramuser_isadmin_quizanswer_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.ManyToManyField(related_name='QuizResult', to='zoo.quizanswer', verbose_name='Quiz Answer'),
        ),
    ]
